### ISSUE TITLE
HUGE headings in new native Obsidian WYSIWYG

### ISSUE THREAD

**Issue by ryadaj** [ceciliamay/obsidianmd-theme-primary#11]
LOVE your theme. Is my new favourite.

Since native WYSIWYG release, headings are now ginormous. Can confirm I'm not simply zoomed in or accidentally increased text size.

![Screen Shot 2021-11-10 at 17 45 25](https://user-images.githubusercontent.com/82765301/141205932-4d411eb0-caa1-4c37-8fbb-100eed04ead0.png)

**Comment by kometenstaub** [comment]
Did you update the theme? That should be fixed with 0.2.0.

**Comment by ceciliamay** [comment]
Hmmm... I do not experience any issues like this... and my Obsidian is up-to-date. I will be honest that the headings are large compared to other themes _(customization is coming soon hehe)_ but certainly not ginormous like in the picture. That issue was previously present in the iOS version though as @kometenstaub have referred to above, but I have fixed it in 0.2.0. Please let me know if you've updated the theme, and I'll try asking other macOS users if they experience this!!

**Comment by ceciliamay** [comment]
@ryadaj I just pushed a trial update for the theme by changing the `em` of the font-sizes to `rem` - a tip I got from SIRvb!! Could you try it out and see if the header sizes in native WYSIWYG is back to normal now? (I don't have spare to pay for insider build, so I can't test it out yet, I apologize 😭)

**Comment by ryadaj** [comment]
It's fixed! :) sorry for my slow reply, I was... well, I was sleeping haha.

But yes, all good now!!
