### ISSUE TITLE
Superscript "º" displayed as "o"

### ISSUE THREAD

**Issue by Frostnuggets** [ceciliamay/obsidianmd-theme-primary#126]
The title says it all: the **º** symbol is displayed as a regular **o**.

**Comment by ceciliamay** [comment]
Hello there @Frostnuggets ! This is definitely a font's character support issue. This can be solved by changing the font that supports it. If you haven't, you can download the Style Settings plugin so that you can get access to some preset fonts I've set up available for Primary:
![image](https://user-images.githubusercontent.com/90643719/167277903-571c2a38-2033-4c4f-9629-447f9c45e24e.png)

The º symbol is supported in all the other fonts (Lora, Inter, Roboto Slab, and Quicksand) except for Karla (which is the theme's default). You can also set a custom font if you'd like!
