### ISSUE TITLE
Several aspects not rendering in native WYSIWYG

### ISSUE THREAD

**Issue by ryadaj** [ceciliamay/obsidianmd-theme-primary#13]
I imagine you've had enough of my by now, but just noticed a few other items I wanted to bring to your attention, some of which may belong with Obsidian devs (but I'm not very savvy, so I dunno—feel free to ignore!):

- tag pills not rendering in edit mode
- page width tightens up in preview mode, but this is not in WYSIWYG edit mode
- bullets remain as hyphens in edit vs. preview
- arrows next to headers different in edit vs. preview mode
- edit: also noticed large spaces between text and headings

![Screen Shot 2021-11-11 at 07 58 21](https://user-images.githubusercontent.com/82765301/141308248-ca592cb1-0d41-4d07-bd97-d07151b59a1c.png)
![Screen Shot 2021-11-11 at 07 58 54](https://user-images.githubusercontent.com/82765301/141308251-403c0285-b77d-4567-8d05-9c4ff9c9886f.png)
![Screen Shot 2021-11-11 at 08 40 04](https://user-images.githubusercontent.com/82765301/141308255-48b707fd-7865-47a2-8cec-26533054cd5c.png)
![Screen Shot 2021-11-11 at 08 40 10](https://user-images.githubusercontent.com/82765301/141308257-26e1d9df-6880-4895-a475-10bd135bc258.png)

**Comment by ceciliamay** [comment]
I heard from other developers that there has been changes to some class names since the new WYSIWYG update has been pushed so parts in themes got wrecked (thus the discussion around theme devs needing to update their themes on Discord) — but since it's only still in beta, I was advised to not really work on anything yet as many changes are to come and could even end up just being a blip! I think this is a very fair point (also I'm sorta biased because as you might've read I am no insider so I can't really test anything out 😭)

BUT I really, really appreciate all the issues you've reported, and they will definitely be kept in mind! 🙏 If these issues transfer over to the official release — I'll update it ASAP!😉

**Comment by ryadaj** [comment]
Ah thanks for the inside scoop on how theme devs should approach these issues! I will stop spamming github with issues in that case 🤣 

Thanks again for a BEAUTIFUL theme ❤️

**Comment by ceciliamay** [comment]
Hey!! I hope you're still enjoying Primary. It's now at v.1.0 - releasing a mega update with tons of fixes, including full v.0.13+ support!! ✨🥳
