### ISSUE TITLE
Color folder snippet not working

### ISSUE THREAD

**Issue by wolfgrrl** [ceciliamay/obsidianmd-theme-primary#142]
Added this to my snippets directory and loaded it. Colored folders do not appear. Ob 0.14.15.

**Comment by ceciliamay** [comment]
Hello @wolfgrrl !! Have you changed the code so that the style applies to your name of folders?
![image](https://user-images.githubusercontent.com/90643719/174297033-527829bd-750c-45bd-bf32-6485c2522498.png)

the code that is underlined in blue are the ones that you need to change. These are originally what my folders look like, you'll have to change it to your folder's names. this occurs repeatedly throughout the code for about 8 different folder names (or data-paths). You can add or remove as much as you like. Let me know if this helps!!

**Comment by ceciliamay** [comment]
Hello @wolfgrrl !! Have you tried out the suggestion above? Let me know if it's working and if it's all good, I'll close the issue. Thanks!

**Comment by wolfgrrl** [comment]
I am all set. Thank you!
