### ISSUE TITLE
Margin Between Blockquotes

### ISSUE THREAD

**Issue by zcysxy** [ceciliamay/obsidianmd-theme-primary#20]
Thanks for this great theme! I think there is a small place that can be improved: the margin between successive blockquotes. Now successive blockquotes are attached to each other with zero margin. I think it would look better with some margin space between them. 😄 

![image](https://user-images.githubusercontent.com/48207708/142399331-22b30d1c-c998-4a9b-bd84-a7d047beb72d.png)

**Comment by ceciliamay** [comment]
Hey there @zcysxy ! I just released a teeny tiny [v.0.2.6 update](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.0.2.6) fixing this! It should now be properly margined 😉

Also, I just want to say that I really love seeing the theme with other languages - especially non-Latin characters! I really appreciate you sending a screenshot. It makes me happy to see my work being used from all over the world 💛(also it probably gave me strong nostalgia and bias because I used to study Mandarin when I was younger Haha!)
