### ISSUE TITLE
Accessibility/Font sizes

### ISSUE THREAD

**Issue by diego898** [ceciliamay/obsidianmd-theme-primary#43]
Hello,

I have the font size slider turned all the way up in Obsidian, as I have bad vision.

But this does not affect the font size of menus, dropdowns, sidebars, or especially code blocks inside a note itself.

Is it possible to change all of these sizes as well?

I know you can zoom in to the entire obsidian UI, but then other things blow up and I have to end up scaling font sizes way down, buttons are huge, etc. 

Thank you!

**Comment by ceciliamay** [comment]
Okay so I finally figured out how to do this - but will need to do a lot of overhauling some code. I'll try to do my best to deliver this soon!

**Comment by diego898** [comment]
Wow thanks @ceciliamay for looking into this!

**Comment by ceciliamay** [comment]
Hello @diego898 !! Thank you so much for your continued support and patience 🙏. I've finally added this option in this recent update: https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.4.8

It's still on a sort of beta - but I'm hoping you could provide me feedback on it so that I can improve this in future releases. I really like this suggestion because I think its a great accessibility option! I will close this issue for now (because I like closing older issues lol 😂) but feel free to add a new issue if you'd like anything fixed/suggestions.
