### ISSUE TITLE
Scrollbar width

### ISSUE THREAD

**Issue by aubreyz** [ceciliamay/obsidianmd-theme-primary#55]
Fantastic theme - thank you Cecilia!

Only issue I have is that on my fairly big monitor the vertical scrollbar width is WAY too narrow. It takes 10 seconds of effort to accurately position the mouse to grab it. What CSS do I need to alter to make it wider. 

In fact it is hard to even see it quickly

![scrollbar](https://user-images.githubusercontent.com/25100168/151249339-dec48cb0-a052-41cd-9916-0cfb0f264ccf.jpg)

**Comment by ceciliamay** [comment]
This one will be fixed in the next update!! I found out that this was due to misplacing a style for the sliding panes plugin (the error is that it kept hiding behind the note titles, found out about it on another theme i'm commissioned to do). Be rest assured that the scrollbar will be visible by the weekends. 

On that note, could you check out scrollbars with sliding panes turned off and maybe let me know if you still want a thicker one? I like the thin scrollbars but might consider adding a setting if you'd like it wider (haven't had a request for that so i am putting it off until it is needed). I've been considering what to add for the style settings update soon in Feb 😄

**Comment by aubreyz** [comment]
Thanks Cecilia - I can confirm that sliding panes is partially to blame (when some scrollbars disappear completely).

However you are choosing a scrollbar width that is way to narrow anyway for comfort of most people I would think. You seem to be a quarter of the default width (by eye anyway), and for a quick scroll that is too small a target. You can perhaps make it 20% smaller but I wouldn't go down much more than that. 

Screengrabs of you versus default theme below on my machine

If you want to save a few pixels of horizontal screen estate I would reduce the left and right icon bar by about 4 pixels each if that is possible

![default theme](https://user-images.githubusercontent.com/25100168/151380624-525909a6-c19a-4e2a-baef-811a85599c3a.png)
![cecilia](https://user-images.githubusercontent.com/25100168/151380645-ebe8c580-f871-43cf-b054-f2a6bbb9fe90.png)

**Comment by ceciliamay** [comment]
Thank you for your suggestion!! So far, I only have this complained once (from you specifically). I would like to make a defense for the tiny scrollbars, that a lot of people these days don't grab onto the scrollbars and instead just use the scroll wheel to scroll. My current proposed solution is to widen the scrollbar only on hover or have a style setting to adjust the width - I really don't want to have a visual cue for the scrollbar other than to see how deep I am in a tab or note. What do you think?

**Comment by aubreyz** [comment]
Not sure about this. The web seems pretty divided - about half and half, and may be an age relationship too. Wheeling is much more stressful for tendons than the scrollbar. 
If it widens enough on hover that may work well though. 

Lots of people have accessibility issues, including young spring chickens. 

And no, I am not being "complaining" - you have done great work here.

**Comment by ceciliamay** [comment]
Thank you so much for your input!! I'll keep this in mind, test some things out and will update you on this 😄 Thank you for bringing light to this discussion!

**Comment by tyindeepit** [comment]
If I may chime in. I agree that the scrollbar is too small to grab and wish it's wider. I don't have sliding pane installed.
Just throwing some idea; Is it possible to make the scrollbar wider on hover like native Mac OS application? I know that Mac OS Obsidian doesn't do this also. Is it because it's electron?

**Comment by ceciliamay** [comment]
Wanted to let you guys know that Style Settings with a Mac-like scrollbar option will be out on the next update (at best by Monday)!! The scrollbar becomes wider on hover like on Mac OS. The code is done. I'm just finishing off some other feature the update will come with. @tyindeepit  @aubreyz 😄

**Comment by ceciliamay** [comment]
Hello folks!! [I just released v.1.2 for Primary](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.2.0) with the Style Settings update!! You can change the look of the scrollbar now through this. You can also change graph view colors, header colors, fonts and more! Let me know how its looking 🥳😄
