### ISSUE TITLE
HowTo - Customization Elements - Demo Features File? 📖 

### ISSUE THREAD

**Issue by KyoKazehaya** [ceciliamay/obsidianmd-theme-primary#59]
Hello Cecilia! 

I've just downloaded your theme and I like how cozy it is! The rounded buttons, colors, and overall feel is great ❤️ 

I'm kinda new to Obsidian and when I see screenshots of people around I don't really know how I can get these things to modify the theme and make it look nicer 😞 

I saw from the Readme some "elements" that look really nice! But I'm not sure if they're from a plugin or are directly supported by the theme.

![image](https://user-images.githubusercontent.com/11358135/152038241-04747a41-ec8d-4abb-916a-da729b285b7a.png)

From the image, I see that "Info" is from the Admonition plugin. But how do you create the little boxes like the one that says "Metadata" and "Note"? If you had a little list of plugins or even a .md file to showcase the features it would be amazing and really helpful! 😄 

I know this is a long shot but I also saw your theme thanks to an user that posted this screenshot of their workspace:

![image](https://user-images.githubusercontent.com/11358135/152038490-9559663c-4968-4a80-b00c-8debbb12303a.png)

Do you know if there is an existing plugin to make your folders split into colorful categories? Or do you think that the user has added custom CSS to make it?

I realize that maybe this questions are more related to general knowledge of Obsidian but sometimes is a bit difficult to search things online as I don't really know the exact name of these things 😅 

Any help/insight it's greatly appreciated! ⭐

**Comment by ceciliamay** [comment]
Hey there @KyoKazehaya !! I'm glad you're enjoying Primary's coziness 🤗~ I'll go through some of these things really quickly, and will attempt to redirect you to some resources! The general advice is that you can get more answers through the [Obsidian Forum](https://forum.obsidian.md) or through the [Discord](https://discord.gg/veuWUTm)! The community is very active and should you have any questions, I think you're likely to get an answer.

1. the Metadata box will show up if you add metadata (using yaml frontmatter) at the top of your .md note. 
![howtoyaml](https://user-images.githubusercontent.com/90643719/152046935-5010c1b9-0928-4a32-838f-7c27869b88a7.gif)
it will automatically show up when you add metadata to your note! the box on top of that metadata block though, will only show up after you toggle on the **Show Frontmatter** setting that you can find at Settings > Editor > Show Frontmatter :D
2. for the "Note" box - that can be generated by making an `<aside> ... </aside>` html block on Obsidian - but it varies theme to theme. unfortunately, because of some conflict with Obsidian's recent update, I recently _temporarily_ dropped support of asides. It's coming soon though!
3. the colorful folders are custom CSS that a user adds through a snippet! it's on the roadmap to offer an official working snippet for Primary users but i have yet to have time to set that up. it will come soon though! for now, i recommend asking on the discord at the appearance channel! tons of users over there use colorful headers 😄 [another resource i found](https://forum.obsidian.md/t/iterative-rainbow-folder-colors-css/21066?u=cecilia_may)

That's about what I can write for the time being. I appreciate you posting this because it reminded me that I have a documentation to do!! Thanks again for the kind words and I hope you continue enjoying Primary! 😄

**Comment by KyoKazehaya** [comment]
Hi @ceciliamay !! omg thank you for such detailed answer 😭 ❤️ I'll join the Discord and the Forum! 🙌 

1. Thank you for the tip!! Managed to do it on my vault ⭐  

![image](https://user-images.githubusercontent.com/11358135/152075024-f0397caa-1b38-429f-ba99-92df5a210df7.png)

2. I sometimes forget that we can add HTML tags to our documents 😅 I'll be looking forward for that update because these little boxes look lovely and it would improve my existing notes a lot! ✨ 

3. Aw, thank you for finding the resource in the Forums! That looks like something I can try to fiddle with but I'll follow your suggestion and I'll ask the folks of Discord 🙏 

And you're most welcome, thank you for creating this theme, sometimes what people need is a comfy place to write their notes and you're achieving it! 😄 I've added a little support to your Ko-Fi page as my sincere appreciation to your work and your help ⭐ I'm looking forward for the new and shiny future updates! 🎉
