### ISSUE TITLE
Add support for Outliner plug-in

### ISSUE THREAD

**Issue by feeei** [ceciliamay/obsidianmd-theme-primary#79]
Hi! This is my first time on Github so I am not familiar with how this all works. Wanted to leave a note about support for the Outliner plugin, as I've noticed the lines don't show up in Primary. Don't know if this is an easy fix or not, but it greatly improves the experience for people who like to write in outline-style interface. I'm using Obsidian and Logseq alongside one another, and Logseq is similar to Roam in its outline/block style note taking, so support for this plugin would bring even greater interoperability between Obsidian/Logseq. Pic 1: Default template showing outliner lines for bullets, Pic 2: Primary snippet of same text, but no outliner lines for bullets. Note that bullet spacing is actually better in Primary for accommodating outliner lines than the default.
<img width="221" alt="Screen Shot 2022-02-23 at 9 30 57 PM" src="https://user-images.githubusercontent.com/4633168/155446122-376c5c2d-8861-44eb-a704-bf75c34cdc05.png"> <img width="175" alt="Screen Shot 2022-02-23 at 9 32 08 PM" src="https://user-images.githubusercontent.com/4633168/155446313-48c6c8e7-477c-426c-b1a2-4e3d46510b52.png">

I apologize if I'm doing this wrong, please send me a message if I'm missing something!

**Comment by ceciliamay** [comment]
Hey there @feeei !! I would really love to support this plugin - I actually used to have Outliner. But ever since the LP update, it looks like vslinko dropped support for themes other than the default theme. It is written in his documentation. I do not get any of the Outliner function in other themes - whether Minimal or other top themes. Only Zoom plugin works. I only get the Outliner functions in the default theme. [See this part](https://github.com/vslinko/obsidian-outliner#improve-the-style-of-your-lists) of the documentation.

If you are looking for just the indentation guide, Obsidian has rolled out **Indentation Guides** toggle feature under Settings > Editor > Indentation Guides. If it's not there yet, then it is in Insider - which will probably roll out soon :>

But yeah -- I'm bummed out too. For now I will close this but will keep it under the `Hmmm...` column in my roadmap in case a better solution for this comes up. Thanks again for the report, kind words and support!!

**Comment by feeei** [comment]
I appreciate you looking into it and pointing me to the indentation guides! 🙏 PS still using this theme on all my vaults, it’s the best 😍

**Comment by alexfazio** [comment]
Appreciate you working on this. Primary and Outliner are my core features!
