### ISSUE TITLE
[Suggestion] remove active line background focus color from gutter

### ISSUE THREAD

**Issue by jsmorabito** [ceciliamay/obsidianmd-theme-primary#8]
The only other app I've seen that uses the text input focus styling applies the styling to the div that the text is in rather than also being applied to the gutter which is how it is currently styled in this theme. I don't think styling the gutter is necessary, but maybe it is for some workflows? Curious to know your thoughts!

From Athens Research:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/46250921/140759618-956a7564-2fde-4145-ac29-8e0185f3bde0.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/46250921/140759724-3f1cf5ec-06b3-4956-a829-deeec3249df9.png">

**Comment by ceciliamay** [comment]
Thank you for this suggestion!! Because Primary was originally designed for my personal use, I totally understand why you'd rather prefer not having the active line styling for the gutter. While coding this theme, I personally felt that I like the whitespace that styling the gutter has created! But I agree - this is a very nuanced and somewhat unorthodox design and others may not prefer it. To please both ways - what do you think of adding it as a toggle in the style settings? or have a section for styling the active line on its own (toggle on/off, gutter styling on/off, custom colors)?

Thanks again for suggesting this, and I'd love to know your thoughts on reply!!

**Comment by jsmorabito** [comment]
A style settings toggle would be awesome! What might be cool, if you have plans for doing custom color settings similar to Yin and Yang, would be to have the active line background color change according to the users selection of the primary/secondary/tertiary color so that the themes visual language is consistent. I've been enjoying the theme a lot btw. Thanks for making it 🙏
