### ISSUE TITLE
Latest update seems to ignore style plugin settings, ignores header font and color, ignores CSS snippets

### ISSUE THREAD

**Issue by nousernameavailableanymore** [ceciliamay/obsidianmd-theme-primary#92]
I applied the latest update and everything seemed to work fine.

However, after restarting obsidian, a lot of things were broken
1. I cannot even open the style settings via the "open style settings" command (see attached screenshot, works fine in Minimal).
2. When opening style settings via the icon, you can see that all settings seem to be ignored (vault title...), this also applies to fonts and colors set for headings
3. CSS snippets (for example using multiple columns in admonitions) are ignored / do not work.

This can be somewhat fixed by changing to another theme and then back to Primary.
It will break again after restarting Obsidian with the latest version of Primary (which is most likely why this wasnt noticed at first, as the "old" / working version of Primary theme acted like another / different / working theme and the issues only seem to occur when Obsidian is actually started with that latest version).

I already uninstall and re-installed Primary > same issue.
Issue does not occur (at least the CSS part, the other stuff is Primary specific) with other themes (tested on default and minimal)

Is there a manual way to revert back to the previous version?

![image](https://user-images.githubusercontent.com/45376324/158497752-2c91d723-fbab-4c28-9fe1-cbce5d516857.png)

![image](https://user-images.githubusercontent.com/45376324/158497820-e7ad4cf4-7f3d-48f1-aafe-72fbf1e35e93.png)

![image](https://user-images.githubusercontent.com/45376324/158497983-3c0ac14e-9319-4fd3-a059-77132fbf0b71.png)

**Comment by nousernameavailableanymore** [comment]
Just confirmed that this is an issue with the latest version by reverting back to previous version which fixed all the issues.

I m a total amateur when it comes to css, but if I had to guess, then there is probably a missing closing bracket or something similar somewhere :D

**Comment by ceciliamay** [comment]
Hmmm... I really can't replicate this issue on my end. I use Style Settings on my personal vault and use both Hide Vault Title toggles — they are working fine. I've updated Primary multiple times to triple check. This also means that I use Style Settings and the command to open Style Settings on a new pane is also working fine.

I checked it in my dev vault too.

I checked it again by creating a new vault, and just adding Primary and the Style Settings plugin. All of the settings, toggles and color pickers are working as expected. 

I went a step further and checked the code differences in my commit, and I don't see any missing brackets or semicolons.

I also tried checking it with SlRvb and it's also working fine on their end...🤔
![image](https://user-images.githubusercontent.com/90643719/158529460-c32a0d6d-5921-472f-aa84-d2fa5e9d6708.png)

Have you tried reinstalling Obsidian?

**Comment by nousernameavailableanymore** [comment]
Ok, that took quite some time (and many tests) to figure out whats going on here.
The issue is caused by the new "Preset Bullet Color" setting in "Lists"

**Steps to reproduce:**
1. Have Primary Theme 1.3.1 installed
2. Make changes to Primary theme in Style Settings Plugin (for example set font or color of headings, hide header...)
3. Update to 1.3.2.
4. Change "Preset Bullet Color" (Style Settings Plugin - Primary Theme Settings - Note - Lists) from default ("faint") to "muted"
5. Close Obsidian
6. Reopen Obsidian

**Expected Result:**
theme settings in Style Settings plugin should be retained

**Actual Result:**
theme settings (and some CSS snippets) are ignored

(by the way: has re-installing Obsidian ever solved anything? At least not from my experience.)

**Comment by ceciliamay** [comment]
Hello there @nousernameavailableanymore ! Thanks for digging into this.
I was able to replicate the steps you've laid out. Indeed, it is because of the bullet color setting - but not as expected. I didn't get any of the code wrong. For some reason, Style Settings cannot recognize the "Custom Bullet Color" option - where the user gets to pick their own colors with a color picker. I tried various workarounds and nothing worked. An error in the console prompts and says invalid format. This does not happen to my other settings. It might be a Style Setting bug of sorts.

It is resolved now but because of the weird phenomenon - custom bullet color has been removed. Preset bullet colors are staying though! Thanks for reporting this issue! 🎉

---

Also - yes, reinstalling apps may solve software issues. Do we developers know what exactly goes under the hood to make it a viable solution? No. But the outcome of trying tells us a lot. It makes sure that we will be taking in the problem from a clean fresh slate. It is no different from factory resetting - which is why there is that option. It may or may not solve the problem - like any other solution. The point of why I have suggested that is for solving by elimination. i.e. if you, the user, reinstalled Obsidian and the problem doesn't occur anymore - then Obsidian had some weird mix up in the files along the way (which is possible even without the developer's intent, or yours),. If you, the user, reinstalled Obsidian and the problem still occurs - then we can say that Obsidian has nothing to do with it and that leaves us with only looking at the problem from the user standpoint. Especially since I wasn't experiencing this problem, the reinstall could also let me know if it is a theme/dev issue or a user issue (which has happened in the past - no one knows why it works). That could mean theme problems, snippet interferences, or plugin bugs. No one knows. It doesn't hurt to do a simple reinstall, which I had to do on my end too because the bug was highly unexpected, and I couldn't pinpoint the problem. Not moving forward with a hypothesis doesn't prove anything.

In recent updates, grabbing the new Obsidian installer has solved some problems. This is because of the bug from Electron, and an update/fresh install was needed.

I went on an extended explanation so you would understand why I have suggested such. I apologize if wasn't an elegant one, but it was a hypothesis nonetheless. Let me know if you have any other issues!
