### ISSUE TITLE
Highlights color depends on ordering of highlight, bold, and italics

### ISSUE THREAD

**Issue by arisp99** [ceciliamay/obsidianmd-theme-primary#97]
Hi there! First of all, this is an amazing theme—thank you so much for all your hard work!

I was playing around with the multicolored highlights and noticed that you will get different colored highlights depending on the order of the highlight, **bold** or _italics_. For instance, I would expect that the following two lines of text appear the same:

> \*==highlight nested in italics==\*
> ==\*italics nested in highlight\*==

In live preview mode, they do!

<img width="241" alt="image" src="https://user-images.githubusercontent.com/19840652/160024152-fba71d43-78fd-4e67-bd6e-04eee92f6e25.png">

However, in reading mode, they don't...

<img width="241" alt="image" src="https://user-images.githubusercontent.com/19840652/160024145-eebdd4d8-d285-4dcd-b73e-6e484704367e.png">

Would it be possible to have the same highlight color regardless of the order of the highlights, bold, and italics?

---

I tried to do some digging around as to why this might be the case and I have _some idea_, but forgive me if my analysis is a bit off as I have **very** little SCSS/CSS/HTML experience. Inspecting the developer window, we get the following HTML code:

```html
<!-- \*==highlight nested in italics==\* -->
<div><p><em><mark>highlight nested in italics</mark></em></p></div>

<!-- ==\*italics nested in highlight\*== -->
<div><p><mark><em>italics nested in highlight</em></mark></p></div>
```

Yet, the SCSS defines the background color only when `mark` is a subclass of `em`:

https://github.com/ceciliamay/obsidianmd-theme-primary/blob/c27764a67f92301460bb80254caa4ce013c2e94f/scss/30_note/_md-emphasis.scss#L90-L93

It seems that it is not possible to specify the SCSS for superclasses (i.e. `mark` when it has a subclass `em`) but is there some other way to ensure the highlight colors are always the same? It may very well be that this issue cannot be resolved...

**Comment by ceciliamay** [comment]
Hello there @arisp99 !! Thank you for the soo much kind words!! 🙏

Yes, the issue cannot be resolved, unfortunately :< I tried very hard and very long to find ways to make it so that the highlights will be just like how LP does it. But since there are no classes for multicolored highlights on Preview, :😔.

The problem if I try to specify `mark em` is that the highlights will be colored 2 times (1 for the `mark` html element; and 2nd for the `em` in `mark` - another html element). I hope you understand what I mean.

So, the only way to make multicolored highlights work as expected is to first wrap them in ==highlight== syntax, then the bold or italic. I tried sooo hard and long to figure this out. I also looked into other themes for potential solutions but only find them with the same problems :( The only way to solve this is to have Obsidian give `mark` classes when bold/italic/bold+italic. `<mark class="strog em">`

**Comment by arisp99** [comment]
Thanks @ceciliamay for clarifying the issues surrounding this issue. I will go ahead and close this issue as it cannot be solved. 

It may actually be worthwhile to report this issue to the Obsidian devs as well. I'd be happy to do so when I get a chance. Perhaps they would consider changing Obsidian's source code to add additional subclasses to the `mark` element (although I am not sure how difficult that would be...).
